''' Diffie-Hellman algorithm example '''
import math

def publicKey(s):
    return ((g**s) % p)

def sharedSecret(secretKey,publicKey):
    return ((publicKey**secretKey) % p)

def isPrime(n):
    for x in range(2,int(math.sqrt(n))+1):
        if n % x == 0 :
            return 0
    return 1

p = int(input('Enter a prime number p '))
if not isPrime(p):
    print("not a prime number")
    exit()

g = int(input('Enter a base number g '))
a = 6 # Alice's secret key.
b = 15 # Bob's secret key.
A = publicKey(a)
B = publicKey(b)

print('Alice public exchange key =',A)
print('Bob public exchange key =',B)
print('Shared secret generated by Alice =',sharedSecret(a,B))
print('Shared secret generated by Bob =',sharedSecret(b,A))
